apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${KUBE_NAMESPACE}
  name: frontend-ingress
  annotations:
    cert-manager.io/cluster-issuer: cluster-certificate-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - ${KUBE_DOMAIN}
      secretName: frontend-tls
  rules:
    - host: ${KUBE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 5000